M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Mo 08 Mai 2023 08:47:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-08T08:47:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X2.4016Y-5.0016
X5.4724Y-5.0016
T0
M30
